---
abstract: 'Perl twist on the most useful PHP function ever - addslashes'
author:
  - 'James Aitken <jaitken@cpan.org>'
build_requires:
  Test::More: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Addslashes
requires:
  Encode: 0
  Exporter: 0
  feature: 0
  parent: 0
  perl: 5.010
  strict: 0
  utf8: 0
resources:
  bugtracker: https://github.com/LoonyPandora/Acme-Addslashes/issues
  repository: git://github.com/LoonyPandora/Acme-Addslashes.git
version: 0.1.1
